### ISSUE TITLE
[server] Allow setting different basepath. And support for static web services.

### ISSUE THREAD

**Issue by pinghe** [agnesoft/agdb#1104]
Allow setting different basepath. 
And support for static web services.

**Comment by agnesoft** [comment]
Completed by #1105 

@pinghe Hi, this is now done. I have included changes to the APIs to allow use of basepath as well. I have simplified it that it just takes connection string that may optionally include the required prefix instead of splitting host/port/baseapath as before. It will be included in the next major release because there are several breaking changes (like the constructor I just mentioned) that require increase of major semantic version.
