### ISSUE TITLE
[api] TypeScript API Bugs and Proposed Solutions

### ISSUE THREAD

**Issue by pinghe** [agnesoft/agdb#1131]
I've identified a few bugs in our TypeScript API implementation that need to be addressed. Below are the issues and my proposed solutions for each:

Bug 1: Axios baseURL Not Set

Issue: The axios instance is not configured with a baseURL, which causes issues when a custom prefix is set and needs to take effect.
Proposed Solution: In client.ts, set the baseURL for the axios configuration as follows:
````
AgdbApi.api = new OpenAPIClientAxios({
    definition: `${address}/api/v1/openapi.json`,
    axiosConfigDefaults: {
        baseURL: `${address}`, // Set axios's baseURL
    },
});
````
Bug 2: InsertNodesBuilder Not Passing IDs

Issue: The InsertNodesBuilder is not passing ids, which results in them not being effective.

Proposed Solution: In query_builder.ts, modify the ids method to ensure ids are passed correctly:
````
ids(
    ids:
        | QueryId[]
        | Components.Schemas.QueryType
        | Components.Schemas.QueryResult,
) {
    this.data.ids = intoQueryIds(ids);
    return new InsertNodesIdsBuilder(this.data);
}
````
And update the InsertNodesIdsBuilder class constructor to handle undefined data properly:
````
class InsertNodesIdsBuilder {
    private data: Components.Schemas.InsertNodesQuery;

    constructor(data: Components.Schemas.InsertNodesQuery | undefined) {
        if (data) {
            this.data = data;
        } else {
            this.data = {
                count: 0,
                aliases: [],
                ids: { Ids: [] },
                values: {
                    Single: [],
                },
            };
        }
    }
}
````
Bug 3: InsertEdgesBuilder Has Similar Issue as Bug 2

Issue: The InsertEdgesBuilder faces the same problem as InsertNodesBuilder where ids are not being passed effectively.

Proposed Solution: In query_builder.ts, adjust the ids method for InsertEdgesBuilder similar to the solution for InsertNodesBuilder:
````
ids(
    ids:
        | QueryId[]
        | Components.Schemas.QueryType
        | Components.Schemas.QueryResult,
) {
    this.data.ids = intoQueryIds(ids);
    return new InsertEdgesIdsBuilder(this.data);
}
````
Ensure the InsertEdgesIdsBuilder class is correctly handling the query data:
````
class InsertEdgesIdsBuilder {
    private data: Components.Schemas.InsertEdgesQuery;

    constructor(query: Components.Schemas.InsertEdgesQuery) {
        this.data = query;
    }
}
````

I believe these solutions will resolve the current bugs and improve the stability and functionality of our API.

Thank you for your review and consideration.

Best regards,
pinghe

**Comment by michaelvlach** [comment]
Thanks for reporting this, I will get it fixed.

**Comment by agnesoft** [comment]
@pinghe This is now fixed. I have dramatically improved the ergonomics of the TS API. For example there are many wrappers now that lets you use the native TS types without the need to specify the full JSON represenation (still possible though). Similarly many functions that required array now can accept single param as well that will be internally made into an array.

Lastly and most importantly I have made it so that client is no longer global and can be instantiated as many times as needed with possibly different hosts / logins. I have also added `login()` shorthand to avoid login+setting tokent (still possible though).

As part of this I have also significantly revamped and improved on the API testing but please let me know if you encounter any issues!

**Comment by pinghe** [comment]
@agnesoft  Thank you. I will update to the latest version and verify it in the near future.
