### ISSUE TITLE
[db] Add values() to search()

### ISSUE THREAD

**Issue by teodosin** [agnesoft/agdb#1244]
Hey again :) Back with another feature request. 

I found it odd that a search() query can't return the key-value pairs from nodes or edges. It feels like a natural thing to do but is as of yet unavailable. Currently we have to do two queries to get data from a search. The first one would be to get the node and edge id's from the search() and the second one would be to use those id's to run a select() query to get the actual data. 

```rust 
// Currently have to do this
let elems = db.exec(&QueryBuilder::search.from("root").query;

let ids: Vec<DbId> = links.unwrap().elements.iter().map(|elem| {
    elem.id
}).collect();

let full = self.db.exec(&QueryBuilder::select().values(vec![]).ids(ids).query());


// But why not just this?
let full = self.db.exec(&QueryBuilder::search().values(vec![]).ids(ids).query());
```

I would presume that having to run two queries to essentially accomplish one thing would have an effect on performance, even if marginal. And of course this would be more ergonomic. If there is a technical reason why this couldn't be done, perhaps you could mention it on the [queries doc page](https://agdb.agnesoft.com/docs/references/queries#search).

**Comment by michaelvlach** [comment]
You are right in that users won't really care and the type system will enforce the correct query anyway (I even simulated it in the other APIs in Typescript and PHP so far that they only accept `SearchQuery` where appropriate and not any query). I think you convinced me so I will keep this open and implement the ability to morph seamlessly from search to select as I do agree it is very common and would be very convenient.

A note about the correct order of functions that was done deliberately for readability. :-) I did expect people to use their IDE and LSP like rust-analyzer (or Rust Rover) to get it right but overall point is that it is not a free-form and therefore when you go (or I go) look at othe people's queries they will look exactly the same. Each piece will always be in the same place. With enough of them written you will remember it anyway just like in SQL but it will not leave you wondering "what sorcery is this?" if someone does something weird which is not possible here (unlike SQL). The query system is directly influenced by my frustrations working with SQL (have you ever seen 1000+ lines SQL quey [yes, singular]?). I suppose it's always like this, Graydon created Rust from his frustrations with C++. So transparency, conciseness and "mostly one way to do things" were important to me when designing it. But then again ergonomics are also very important so I am not following some dogma with it, just being mindful of the original principles.

Cheers again for this issue, I would probably keep deliberating instead of finally doing it!
